# H1 TITLE
## H2 TITLE

In [9]:
print("Buy the dip ?")

Buy the dip ?


### Exercise 1: NumPy array.

In [24]:
import numpy as np

numpy_array = np.array([42, 3.1415926,'hello, world!',{'slava':'ukraine'},['putin', 'huylo'], ('ahmad','tea'),{'my', 'horse' , 'is', 'amazing'}, True], dtype='object')

for i in numpy_array:
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'dict'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'bool'>


### Exercise 2: Zeros.

In [7]:
import numpy as np
zeros=np.zeros((300,1), dtype=np.int32)
print('zeros\n',zeros)
reshaped = zeros.reshape((3,100))
print('new\n',reshaped)


zeros
 [[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0

### Exercise 3: Slicing.

In [34]:
import numpy as np

array=np.linspace(1,100, 100, dtype=np.int32)
print(array)
odd_numbers = array[np.where(array%2!=0)]
even_reversed=np.flip(array[np.where(array%2==0)])
replaced=array.copy()
np.put(replaced, np.arange(1, len(array), 3), 0)
print(replaced)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[  1   0   3   4   0   6   7   0   9  10   0  12  13   0  15  16   0  18
  19   0  21  22   0  24  25   0  27  28   0  30  31   0  33  34   0  36
  37   0  39  40   0  42  43   0  45  46   0  48  49   0  51  52   0  54
  55   0  57  58   0  60  61   0  63  64   0  66  67   0  69  70   0  72
  73   0  75  76   0  78  79   0  81  82   0  84  85   0  87  88   0  90
  91   0  93  94   0  96  97   0  99 100]


## Exercise 4: Random.

In [13]:
import numpy as np

rng = np.random.default_rng(888)
normal_array = rng.normal(size=100)
randn_2d = rng.integers(1, 10+1, size=(8, 8))
randn_3d = rng.integers(1, 17+1, size=(4,2,5))
print(normal_array, randn_2d, randn_3d)

[ 2.63038927e-01  5.02565261e-01 -6.03544630e-01  1.16105320e+00
  8.98071505e-01 -1.62755391e-01 -9.68181269e-01  5.05120942e-01
 -2.56207827e-01 -1.69745163e+00  1.69336869e+00  6.32799897e-03
  3.77968815e-03 -1.64070648e+00 -1.34108723e+00  7.12350868e-01
 -1.45685554e+00 -7.54516213e-01 -6.85843859e-01 -5.91052010e-01
  1.37411127e+00 -3.04630902e-01 -6.73853609e-01 -1.80586848e+00
 -5.40548771e-01 -4.91251392e-01  7.39680108e-01  2.71501625e-01
 -6.19142920e-02  1.17770521e+00  1.09704152e+00 -1.38911999e+00
 -6.95696437e-01  8.37534769e-01  9.06290500e-01  8.21394329e-01
  6.20728542e-01 -2.31346273e-01  3.93687465e-01  1.17078525e+00
  9.70762290e-02  4.77549317e-01  2.00284960e+00 -4.66757887e-01
 -3.69496733e-01 -4.61809244e-01  2.08655440e+00  9.88837783e-01
  1.02189658e+00  6.81389649e-01 -3.79780257e-01  6.79683068e-01
  8.88184795e-01 -1.08130766e+00 -5.22903695e-01 -6.96775922e-01
 -7.29571176e-01  1.34755592e+00  3.83166023e-02  1.80026204e+00
 -8.78028786e-01  3.48549

### Exercise 5. Split, concatenate, reshape arrays.

In [19]:
import numpy as np

array1 = np.arange(1, 50+1)
array2 = np.arange(51, 100+1)
union = np.concatenate((array1, array2))
new_shape = union.reshape((10, 10))
print(new_shape)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


### Exercise 6. Broadcasting and slicing.

In [22]:
import numpy as np

ones = np.ones((9, 9), dtype = np.int8)
ones[1:-1, 1:-1] = 0
ones[2:-2, 2:-2] = 1
ones[3:-3, 3:-3] = 0
ones[4:5, 4:5] = 1
print(ones)

[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]
